language: node_js
node_js:
  - "0.6"
  - "0.8"
  - "0.10"
  - "0.12"
  - "4"
  - "5"
  - "6"
env:
  - CXX=
  - CXX=g++-4.8
matrix:
  exclude:
    - node_js: "0.6"
      env: CXX=g++-4.8
    - node_js:
        - "4"
        - "5"
        - "6"
      env: CXX=
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
  - npm update -g npm
